apiVersion: v1
kind: Service
metadata:
  name: event-service
  namespace: events
spec:
  selector:
    app: event
  ports:
    - protocol: TCP
      port: 3006
      targetPort: 3006
  type: LoadBalancer